version: '3.7'

services:
  dc_tgbot:
    image: ${DOCKER_IMAGE}
    depends_on:
      - dc_postgresdb
    networks:
      - internal
    env_file:
      - .env

  dc_postgresdb:
    image: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT_OUT}:${POSTGRES_PORT}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - internal
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-db:


networks:
  internal:
    driver: bridge
